name: Deploy Flutter Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Enable web
        run: flutter config --enable-web

      # Skapa ett tomt Flutter-projekt om repot saknar pubspec.yaml (för mobilredigering)
      - name: Ensure project exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create app --platforms=web
            shopt -s dotglob
            mv app/* .
            rmdir app
          fi

      - name: Install deps
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href=/${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
