name: Deploy Flutter Web (12 veckor med Magnusson)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Enable web
        run: flutter config --enable-web

      # Skapa ett nytt Flutter-projekt (om källkod saknas)
      - name: Scaffold Flutter web app
        run: |
          rm -rf *
          flutter create tolv_veckor_med_magnusson --platforms=web
          shopt -s dotglob
          mv tolv_veckor_med_magnusson/* .
          rmdir tolv_veckor_med_magnusson

      - name: Add dependencies
        run: flutter pub add shared_preferences

      # Skriv vår riktiga appkod
      - name: Write main.dart (profil + 4 pastellrutor + aktivitetslista)
        shell: bash
        run: |
          cat > lib/main.dart <<'DART'
          import 'package:flutter/material.dart';
          import 'package:shared_preferences/shared_preferences.dart';

          void main() {
            WidgetsFlutterBinding.ensureInitialized();
            runApp(const MagnussonApp());
          }

          class AppColors {
            static const red = Color(0xFFFFCDD2);
            static const yellow = Color(0xFFFFF9C4);
            static const green = Color(0xFFC8E6C9);
            static const blue = Color(0xFFBBDEFB);
